
const VERSION = [1, 0];

const MAC_SIZE = 6;

const RBUS_CRC_SIZE = 2;
const RBUS_DEVICE_TYPE_SIZE = 3;

const RBUS_PING_HEADER_SIZE = 2;
const RBUS_PING_FRAME_SIZE = RBUS_PING_HEADER_SIZE + RBUS_CRC_SIZE;
const RBUS_PING_PREAMBLE_RECEIVE = 0x33;
const RBUS_PING_PREAMBLE_TRANSMIT = 0xCC;

const RBUS_DISCOVERY_HEADER_SIZE = 1;
const RBUS_DISCOVERY_FRAME_SIZE = RBUS_DISCOVERY_HEADER_SIZE + RBUS_CRC_SIZE;
const RBUS_DISCOVERY_RX_BUFFER_SIZE = RBUS_DISCOVERY_FRAME_SIZE + MAC_SIZE + RBUS_DEVICE_TYPE_SIZE;
const RBUS_DISCOVERY_TX_BUFFER_SIZE = RBUS_DISCOVERY_FRAME_SIZE + MAC_SIZE + 1;
const RBUS_DISCOVERY_PREAMBLE_RECEIVE = 0x55;
const RBUS_DISCOVERY_PREAMBLE_TRANSMIT = 0xAA;

const RBUS_CONFIRM_HEADER_SIZE = 2;
const RBUS_CONFIRM_FRAME_SIZE = RBUS_CONFIRM_HEADER_SIZE + RBUS_CRC_SIZE;
const RBUS_CONFIRM_PREAMBLE_RECEIVE = 0x5F;
const RBUS_CONFIRM_PREAMBLE_TRANSMIT = 0xAF;

const RBUS_DATA_HEADER_SIZE = 4;
const RBUS_DATA_FRAME_SIZE = RBUS_DATA_HEADER_SIZE + RBUS_CRC_SIZE;
const RBUS_DATA_BUFFER_SIZE = RBUS_DATA_FRAME_SIZE + RBUS_MESSAGE_SIZE;
const RBUS_DATA_PREAMBLE_RECEIVE = 0x50;
const RBUS_DATA_PREAMBLE_TRANSMIT = 0xA0;

module.exports = {
  VERSION,

  MAC_SIZE,

  RBUS_CRC_SIZE,
  RBUS_DEVICE_TYPE_SIZE,

  RBUS_PING_HEADER_SIZE,
  RBUS_PING_FRAME_SIZE,
  RBUS_PING_PREAMBLE_RECEIVE,
  RBUS_PING_PREAMBLE_TRANSMIT,

  RBUS_DISCOVERY_HEADER_SIZE,
  RBUS_DISCOVERY_FRAME_SIZE,
  RBUS_DISCOVERY_RX_BUFFER_SIZE,
  RBUS_DISCOVERY_TX_BUFFER_SIZE,
  RBUS_DISCOVERY_PREAMBLE_RECEIVE,
  RBUS_DISCOVERY_PREAMBLE_TRANSMIT,

  RBUS_CONFIRM_HEADER_SIZE,
  RBUS_CONFIRM_FRAME_SIZE,
  RBUS_CONFIRM_PREAMBLE_RECEIVE,
  RBUS_CONFIRM_PREAMBLE_TRANSMIT,

  RBUS_DATA_HEADER_SIZE,
  RBUS_DATA_FRAME_SIZE,
  RBUS_DATA_BUFFER_SIZE,
  RBUS_DATA_PREAMBLE_RECEIVE,
  RBUS_DATA_PREAMBLE_TRANSMIT,
}