name: hommyn-daemon # you probably want to 'snapcraft register <name>'
base: 18.04
version: "1.0"
summary: Hommyn smarthome daemon
description: Hommyn smarthome daemon
grade: stable
confinement: strict
parts:
  hommyn-daemon:
    source: https://reacthome.net/download/hommyn/daemon/hommyn-daemon-1.0.tar.gz
    plugin: autotools
