name: hommyn-daemon
version: "1.0"
type: base
build_base: core18
summary: Hommyn smarthome daemon
description: Hommyn smarthome daemon
grade: stable
confinement: strict
parts:
  hommyn-daemon:
    source: https://reacthome.net/download/hommyn/daemon/hommyn-daemon-1.0.tar.gz
    plugin: autotools
