name: hommyn-daemon
version: "1.0"
base: core18
summary: Hommyn smarthome daemon
description: Hommyn smarthome daemon
grade: stable
confinement: strict
apps:
  hommyn-daemon:
    command: hommyn-daemon
parts:
  hommyn-daemon:
    plugin: dump
    source: ./build
    organize:
      hommyn-daemon: /opt/hommyn-daemon/hommyn-daemon
      leveldown: /opt/hommyn-daemon/prebuilds/linux-arm64/node.napi.armv8.node
